version: 0.2

phases:

  install:
    commands:

      - echo "install npm v5.3.0"
      - npm install -g npm@5.3.0

      - echo "install local dependancies"
      - npm install

  pre_build:
    commands:

      # - echo "run tests (linting + unit)"
      # - npm test

  build:
    commands:

      - echo "create gatsby (production) build"
      - npm run build

  post_build:
    commands:

      - echo "deploy build to s3"
      - aws s3 cp --acl public-read --recursive ./public/ s3://enhance-digital-gatsby/

  # artifacts:
  #   files:
  #     - '**/*'
  #   base-directory: 'public'
  #   discard-paths: no